
# Set to your project's Clarinet config file
clarinet = "../../demo-project/Clarinet.toml"

# Set where you'd like ESM types output.
# Comment or remove section to skip ESM types
[esm]
# `output` can be a directory or a folder.
# output = "esm/index.ts"
# output = "test/generated/clarigen-types.ts"
outputs = [
  "test/generated/clarigen-types.ts",
  "../core/test/generated/clarigen-types.ts",
  "../../demo-project/esm/index.ts",
  "../clarigen-test/test/generated/clarigen-types.ts",
]

# `esm.after` - script to run after ESM types are generated.
# examples:
after = "pnpm prettier --loglevel error -w ../*/test/generated/clarigen-types.ts ../../demo-project/esm/index.ts"
# after = "echo 'yay'"

# Set where you'd like generated contract docs
# Generate docs by running `clarigen docs`
[docs]
# `output` should be a folder
output = "../../demo-project/docs"
after = "pnpm prettier --loglevel error -w ../../demo-project/docs"
